import { hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import Providers from "@/shared/providers";
import ToggleTheme from "@/shared/components/toggle-theme";
import { Geist, Geist_Mono } from "next/font/google";
import { Metadata } from "next";
import { getMessages, setRequestLocale } from "next-intl/server";
import ToggleLang from "@/shared/components/toggle-lang";

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({ children, params }: Props) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // Enable static rendering
  setRequestLocale(locale);

  // Variables
  const messages = await getMessages();

  return (
    <html
      lang={locale}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body
        className="min-h-full flex flex-col"
        dir={locale === "ar" ? "rtl" : "ltr"}
      >
        <Providers locale={locale} messages={messages}>
          {children}
          <ToggleTheme />
          <div className="flex my-5 mx-auto">
            <ToggleLang />
          </div>
        </Providers>
      </body>
    </html>
  );
}
