type BadgeVariant =
  | "react-default"
  | "Next.js"
  | "next-default"
  | "typescript-default"
  | "tailwind-default"
  | "node-default"
  | "full-time"
  | "html"
  | "main-tech"
  | "cat-badge"
  | "TypeScript"
  | "Tailwind CSS"
  | "destructive"
  | "react"
  | "RHF"
  | "ZOD"
  | "NextAuth"
  | "shadcn"
  | "nextIntl"
  | "React Query"
  | "css"
  | "js"
  | "sass"
  | "bootstrap"
  | "wordpress"
  | "salla"
  | "zid"
  | "notAvailable"
  | "part-time"
  | "remote"
  | "who-me"
  | "case-study"
  | "collaboration"
  | null
  | undefined;
